name: WINNER11
description: Cricket Base Application.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #local store 
  shared_preferences: ^2.2.1
  get: ^4.6.6
  pinput: ^3.0.1
  http: ^1.1.0
  image_picker: ^1.0.4
  dio: ^5.3.3
  jwt_decode: ^0.3.0
  upi_india: ^3.0.1
  connectivity: ^3.0.6
  internet_connection_checker: ^1.0.0+1
  
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  device_info: ^2.0.3
  uuid: ^4.2.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/icon/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For Detailss regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf

  fonts:
    - family: Roboto1
      fonts:
        - asset: fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: fonts/RobotoCondensed-Light.ttf
        - asset: fonts/RobotoCondensed-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For Detailss regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
